### ISSUE TITLE
Open Patients slow

### ISSUE THREAD

**Issue by glhfgg1024** [bastula/dicompyler#110]
Hi Dear authors, thanks for this great tool!

I have a question, once clicking the "Open Patients", the software will re-load all the subfolders again and no cache, this is very slow when the folder contains many patients. Are there any mechanisms to cache the loaded patients (similar to that in 3D Slicer) in this tool? Thanks a lot!

**Comment by glhfgg1024** [comment]
Hi @bastula , thanks a lot for your kind reply and suggestions!

**Comment by bastula** [comment]
No problem! Thanks for your kind words about the project!

If those don't work, let me know or we can close the issue 😄

**Comment by glhfgg1024** [comment]
@bastula ,thanks a lot! I'll close this issue.
