### ISSUE TITLE
dicompyler crash, when I open some dicoms belong to a patient.

### ISSUE THREAD

**Issue by Fhxzh** [bastula/dicompyler#120]
Platform information:
System: Windows
Version: ('post2008Server', '6.2.9200', '', u'Multiprocessor Free')
Python Version: 2.6.6
dicompyler Version: 0.4.2

dicompyler.dicomgui: DEBUG: Reading: E:\NSCLC-Radiomics\NSCLC-Radiomics\LUNG1-001\09-18-2008-StudyID-69331\0-82046\000014.dcm
dicompyler.dicomgui: DEBUG: Reading: E:\NSCLC-Radiomics\NSCLC-Radiomics\LUNG1-001\09-18-2008-StudyID-69331\0-82046\000015.dcm
dicompyler.dicomgui: DEBUG: Reading: E:\NSCLC-Radiomics\NSCLC-Radiomics\LUNG1-001\09-18-2008-StudyID-69331\0-82046\000016.dcm
dicompyler: ERROR: Unhandled exception: Traceback (most recent call last):
  File "P:\python\dicompyler-bdist\dist\baseplugins\2dview.py", line 417, in OnPaint
  File "dicompyler\dicomparser.pyo", line 204, in GetImage
  File "dicom\dataset.pyo", line 398, in _get_pixel_array
  File "dicom\dataset.pyo", line 393, in _getPixelArray
  File "dicom\dataset.pyo", line 375, in _PixelDataNumpy
ValueError: total size of new array must be unchanged

dicompyler: ERROR: Unhandled exception: Traceback (most recent call last):
  File "P:\python\dicompyler-bdist\dist\baseplugins\2dview.py", line 691, in OnMouseMotion
  File "P:\python\dicompyler-bdist\dist\baseplugins\2dview.py", line 551, in OnUpdatePositionValues
  File "dicom\dataset.pyo", line 398, in _get_pixel_array
  File "dicom\dataset.pyo", line 393, in _getPixelArray
  File "dicom\dataset.pyo", line 375, in _PixelDataNumpy
ValueError: total size of new array must be unchanged

This is my feedback of crash information. How can I del with this problem? Thank you very much.

**Comment by Fhxzh** [comment]
From feedback information, crash reason is that those dicom files are modified dicompyler read? But I don't modify the dicom data and I download from official website.

**Comment by bastula** [comment]
I haven't seen that error before. Do you get this error before performing window/level or panning? If it happens on image load, there is an issue with pydicom decoding the correct size of the image.

**Comment by Fhxzh** [comment]
> I haven't seen that error before. Do you get this error before performing window/level or panning? If it happens on image load, there is an issue with pydicom decoding the correct size of the image.

Thanks for your reply very much. I have process this problem just. I have a new problem in loading dicoms. The question is that when I click Open Patient button, the patient is always old patients last time loaded. And select patients of Open Patient button does not have all of my patients. In other words, Open Patient button can only display a few patients.   But this problem can be replaced by click Open Quickly button. I do not kow if this is a bug. Anyway I can get results I need. So appreciate for this application.

**Comment by Fhxzh** [comment]
> I haven't seen that error before. Do you get this error before performing window/level or panning? If it happens on image load, there is an issue with pydicom decoding the correct size of the image.

Thanks for your reply very much. I have process this problem just. This application helps me a lot. Thanks.
