### ISSUE TITLE
Seeking help on how to translate label to dose

### ISSUE THREAD

**Issue by goodsave** [bastula/dicompyler#127]
Hello, bastula
Excuse me. Would you please do me a favor?
From dicompyler, I learned how to convert dose to label (i.e., DICOM coordinates to pixel coordinates). I wonder how to translate label to dose (i.e. pixel coordinates to DICOM coordinates)?
It would be great if I could get your advice.

**Comment by bastula** [comment]
You should be able to just use the patient to pixel lookup table in reverse. That is what is done to show the mouse cursor readout when hovering in the 2D view.

**Comment by goodsave** [comment]
Your suggestion made me suddenly enlightened.
I used to convert dose to dose line of label，so I naturally think about how to convert the dose line of label back to dose. This transformation seems difficult to achieve.
Now I convert dose directly to the dose value label. Then it's easy to convert the dose value label to dose.
We are now doing AI dose generation. Your suggestion is very useful to us，Thank you again.

**Comment by bastula** [comment]
That is great to hear! Please share your finished product or any screenshots when you have a chance! I  am sure others would love to see your work or product too😄.
